---
layout: post
title:  Promise 对象
date:   2017-03-09 18:58:00 +0800
categories: JS
tag: ES6
---

* content
{:toc}

### Promise 

`Promise`，就是一个对象，用来传递异步操作的消息。

`Promise`对象有三种状态：`Pending`（进行中）、`Resolved`（已完成）和`Rejected`（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。

一旦状态改变，就不会再变，任何时候都可以得到这个结果。`Promise` 对象的状态改变，只有两种可能：从 `Pending` 变为 `Resolved` 和从 `Pending` 变为 `Rejected` 。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。

`Promise` 也有一些缺点。首先，无法取消 `Promise`，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，`Promise` 内部抛出的错误，不会反应到外部。第三，当处于 `Pending` 状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

### 用法

```
var promise = new Promise(function(resolve, reject) {
  	// ... some code
});
```

`Promise` 构造函数接受一个函数作为参数，该函数的两个参数分别是 `resolve` 和 `reject` 。它们是两个函数，由JavaScript引擎提供，不用自己部署。

`resolve` 函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从Pending变为Resolved），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；`reject` 函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从Pending变为Rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

Promise实例生成以后，可以用 `then` 方法分别指定 `Resolved` 状态和 `Reject` 状态的回调函数。

```
promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
```

`then` 方法可以接受两个回调函数作为参数。第一个回调函数是 `Promise` 对象的状态变为 `Resolved` 时调用，第二个回调函数是 `Promise` 对象的状态变为 `Reject` 时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受 `Promise` 对象传出的值作为参数。

```
function timeout(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms, 'done');
  });
}

timeout(100).then((value) => {
  console.log(value);
});


var p1 = new Promise(function (resolve, reject) {
	console.log("p1");
  	setTimeout(() => reject(new Error('fail')), 3000);
});

var p2 = new Promise(function (resolve, reject) {
	console.log("p2");
  	setTimeout(() => resolve(p1), 1000);
});

p2
  .then(result => console.log(result))
  .catch(error => console.log(error));

console.log('end');

// p1
// p2
// end
// done
// Error: fail
```

如上例，Promise新建后就会立即执行，然后，`then`方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行。

如果调用`resolve`函数和`reject`函数时带有参数，那么它们的参数会被传递给回调函数。

上面代码中，`p1`和`p2`都是`Promise`的实例，但是`p2`的`resolve`方法将`p1`作为参数，即一个异步操作的结果是返回另一个异步操作。

注意，这时`p1`的状态就会传递给`p2`，也就是说，`p1`的状态决定了`p2`的状态。如果`p1`的状态是`Pending`，那么`p2`的回调函数就会等待`p1`的状态改变；如果`p1`的状态已经是`Resolved`或者`Rejected`，那么`p2`的回调函数将会立刻执行。

### 基本的 api

1.`Promise.prototype.then()`

2.`Promise.prototype.catch()`

`Promise.prototype.catch` 方法是 `.then(null, rejection)` 的别名，用于指定发生错误时的回调函数。

如果异步操作抛出错误，状态就会变为 `Rejected`，就会调用 `catch` 方法指定的回调函数，处理这个错误。另外，`then` 方法指定的回调函数，如果运行中抛出错误，也会被 `catch` 方法捕获。

`Promise` 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个 `catch` 语句捕获。

跟传统的 `try/catch` 代码块不同的是，如果没有使用 `catch` 方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，即不会有任何反应。

需要注意的是，`catch` 方法返回的还是一个 `Promise` 对象，因此后面还可以接着调用 `then` 方法。如果没有报错，则会跳过 `catch` 方法。

3.`Promise.all()`

`Promise.all` 方法用于将多个 `Promise` 实例，包装成一个新的 `Promise` 实例。

```
var p = Promise.all([p1, p2, p3]);
```

`Promise.all` 方法接受一个数组作为参数，p1、p2、p3都是Promise对象的实例，如果不是，就会先调用下面讲到的`Promise.resolve`方法，将参数转为Promise实例，再进一步处理。

`p`的状态由`p1`、`p2`、`p3`决定，分成两种情况。

（1）只有`p1、p2、p3`的状态都变成`resolved`，`p`的状态才会变成`resolved`，此时`p1、p2、p3`的返回值组成一个数组，传递给`p`的回调函数。

（2）只要`p1、p2、p3`之中有一个被`rejected`，`p`的状态就变成`rejected`，此时第一个被`reject`的实例的返回值，会传递给p的回调函数。